[general]
profile = profile.r29
buildroot = /home/toolchain/development/libc++_replacement/tmp/GBS-ROOT/R29-consumer-unused

[profile.r29]
repos = repo.r29-full
buildconf = /home/toolchain/development/libc++_replacement/tmp/R29/buildconf-default.conf

[repo.r29-full]
url = http://127.0.0.1:18835/
