#
# spec file for package glibc
#
# Copyright (c) 2012 SUSE LINUX Products GmbH, Nuernberg, Germany.
# Copyright (c) 2021 Samsung Electronics Co. Ltd.
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.

# Prepare separate ld.so for qemu-accel
%ifarch x86_64 %ix86
%define build_qemu_accel_ld_so 1
# default path in qemu
%define emul_path /emul
%endif

%if !%{defined dlconf_ldconfig_dat_path}
%define dlconf_ldconfig_dat_path "/run/dlconf.dat"
%endif

%define dlconf 1
%define dlconf_all_dirs 1

# This will avoid building some parts of glibc
%define asan_arch x86_64 armv7l aarch64
%define hwasan_arch aarch64
%bcond_with    fast_build

# Always build with gcc due to using extensions of gcc
%define _toolchain_override gcc

Name:           glibc
VCS:            platform/upstream/glibc#8f08a7e30396822a8d969d357822a6ffd56b43fb
Summary:        Standard Shared Libraries (from the GNU C Library)
License:        LGPL-2.1+ and LGPL-2.1+-with-GCC-exception and GPL-2.0+
Group:          Base/Libraries
BuildRequires:  fdupes
BuildRequires:  makeinfo
BuildRequires:  xz
BuildRequires:  gcc-c++
BuildRequires:  gettext-tools
BuildRequires:  libstdc++-devel
BuildRequires:  bison
BuildRequires:  python3-base
%{?asan:
%ifarch %asan_arch
BuildRequires:  glibc-devel-static
%endif
}
%if 0%{?build_tests}
BuildRequires:  toolchain-testing-tool
%endif

%define _filter_GLIBC_PRIVATE 1
%if %_target_cpu == "i686"
# For i686 let's only build what's different from i586, so
# no need to build documentation
%define build_profile 1
%define build_locales 0
%define build_html 0
%else
%if %{with fast_build}
%define build_profile 0
%define build_locales 0
%define build_html 0
%else
# Default:
%define build_profile 1
%define build_locales 0
%define build_html 0
%endif
%endif

%define enablekernel 2.6.16

Conflicts:      kernel < %{enablekernel}
%ifarch armv7l armv7hl
# The old runtime linker link gets not provided by rpm find.provides, but it exists
Provides:       ld-linux.so.3
Provides:       ld-linux.so.3(GLIBC_2.4)
%endif
Version:        2.40
Release:        2.3

Url:            http://www.gnu.org/software/libc/libc.html
Source:         glibc-%{version}.tar.xz
Source5:        nsswitch.conf
Source7:        bindresvport.blacklist
Source8:        glibc_post_upgrade.c
Source9:        glibc.rpmlintrc
%if 0%{?dlconf}
Source999:     dlconf.service
%endif
# For systemd
Source1001: 	glibc.manifest
# Patches auto-generated by git-buildpackage:
Patch0:     d7477af-to-8f08a7e.diff.gz

Requires(pre):  filesystem
Provides:       rtld(GNU_HASH)

%description
The GNU C Library provides the most important standard libraries used
by nearly all programs: the standard C library, the standard math
library, and the POSIX thread library. A system is not functional
without these libraries.

%post -p %{_sbindir}/glibc_post_upgrade
%postun -p /sbin/ldconfig

%package info
Summary:        Info Files for the GNU C Library
License:        GFDL-1.1
Group:          Documentation
BuildArch:      noarch

%description info
This package contains the documentation for the GNU C library stored as
info files. Due to a lack of resources, this documentation is not
complete and is partially out of date.

%post info
%install_info --info-dir=%{_infodir} %{_infodir}/libc.info.gz
%postun info
%install_info_delete --info-dir=%{_infodir} %{_infodir}/libc.info.gz

%package html
Summary:        HTML Documentation for the GNU C Library
License:        GFDL-1.1
Group:          Documentation
BuildArch:      noarch

%description html
This package contains the HTML documentation for the GNU C library. Due
to a lack of resources, this documentation is not complete and is
partially out of date.

%package i18ndata
Summary:        Database Sources for 'locale'
License:        GPL-2.0+ and MIT
Group:          Base/Libraries
BuildArch:      noarch

%description i18ndata
This package contains the data needed to build the locale data files to
use the internationalization features of the GNU libc. It is normally
not necessary to install this packages, the data files are already
created.

%package locale
Summary:        Locale Data for Localized Programs
License:        GPL-2.0+ and MIT and LGPL-2.1+
Requires(post): /usr/bin/cat
Requires:       glibc = %{version}
%description locale
Locale data for the internationalisation features of the GNU C library.

%post locale
for l in /usr/share/locale/locale.alias %{_libdir}/gconv/gconv-modules; do
	[ -d "$l.d" ] || continue
	echo "###X# The following is autogenerated from extra files in the .d directory:" >>"$l"
	cat "$l.d"/* >>"$l"
done
/usr/sbin/iconvconfig

%package profile
Summary:        Libc Profiling and Debugging Versions
License:        LGPL-2.1+ and LGPL-2.1+-with-GCC-exception and GPL-2.0+
Group:          Base/Utilities
Requires:       glibc = %{version}

%description profile
This package contains special versions of the GNU C library which are
necessary for profiling and debugging.

%package devel
Summary:        Include Files and Libraries Mandatory for Development
License:        BSD-3-Clause and LGPL-2.1+ and LGPL-2.1+-with-GCC-exception and GPL-2.0+
Requires:       glibc = %{version}
Requires:       linux-kernel-headers
Requires:       libxcrypt-devel

%description devel
These libraries are needed to develop programs which use the standard C
library.

%package devel-static
Summary:        C library static libraries for -static linking
License:        BSD-3-Clause and LGPL-2.1+ and LGPL-2.1+-with-GCC-exception and GPL-2.0+
Requires:       %{name}-devel = %{version}
Requires:       libxcrypt-devel-static
# Provide Fedora name for package to make packaging easier
Provides:       %{name}-static = %version

%description devel-static
The glibc-devel-static package contains the C library static libraries
for -static linking.  You don't need these, unless you link statically,
which is highly discouraged.

%package devel-utils
Summary:        Development utilities from GNU C library
License:        LGPL-2.1+
Requires:       glibc = %{version}

%description devel-utils
The glibc-devel-utils package contains various binaries which can be helpful during program
debugging.

If you are unsure if you need this, don't install this package.

%package extra
Summary:        Extra binaries from GNU C Library
License:        LGPL-2.1+
Requires:       glibc = %{version}

%description extra
The glibc-extra package contains some extra binaries for glibc that
are not essential but recommend to use.

makedb: A program to create a database for nss

%package obsolete
Summary:        Obsolete Shared Libraries from the GNU C Library
License:        LGPL-2.0+
Requires:       glibc = %{version}

%description obsolete
This package provides some old libraries from the GNU C Library which
are no longer supported. Additional it provides a compatibility library
for old binaries linked against glibc 2.0.

Install this package if you need one of this libraries to get old
binaries working, but since this libraries are not supported and there
is no gurantee that they work for you, you should try to get newer
versions of your software.

%{?build_tests:
%package tests
Summary:       GNU C Library testsuites
License:       LGPL-2.1+
Group:         Development/Building
Requires:      dejagnu
Requires:      fdupes
Requires:      makeinfo
Requires:      xz
Requires:      gcc-c++
Requires:      gettext-tools
Requires:      libstdc++-devel
Requires:      bison
Requires:      python3-base
AutoReqProv:   off
%description tests
This package contains sources and build output glibc
for running testsuites.

%post tests
rm -rf %{_builddir}/%{name}-%{version}
mkdir %{_builddir}/%{name}-%{version}
xz -d < %{_builddir}/%{name}-%{version}.tar.xz | tar x -C %{_builddir}
rm %{_builddir}/%{name}-%{version}.tar.xz

%preun tests
rm -rf %{_builddir}/%{name}-%{version}
}

%{?asan:
%ifarch %asan_arch
%package asan
Summary:     glibc with ASan instrumentation
License:     LGPL-2.1+ and LGPL-2.1+-with-GCC-exception and GPL-2.0+
Requires:    glibc = %{version}
Requires:    rpm

%description asan
This package provides glibc with ASan instrumentation

%post asan
ln -s --force /%{_lib}/libc-%{version}-asan.so /%{_lib}/libc.so.6
%preun asan
ln -s --force /%{_lib}/libc-%{version}.so /%{_lib}/libc.so.6
%endif
}

%{?hwasan:
%ifarch %hwasan_arch
%package hwasan
Summary:     glibc with Hwasan instrumentation
License:     LGPL-2.1+ and LGPL-2.1+-with-GCC-exception and GPL-2.0+
Requires:    glibc = %{version}
Requires:    rpm

%description hwasan
This package provides glibc with Hwasan instrumentation

%post hwasan
ln -s --force /%{_lib}/libc-%{version}-hwasan.so /%{_lib}/libc.so.6
%preun hwasan
ln -s --force /%{_lib}/libc-%{version}.so /%{_lib}/libc.so.6
%endif
}

%{?build_qemu_accel_ld_so:
%package accel-ldso
Summary:       ld.so file for qemu-accel
License:       GPL-3.0+
Group:         Development/Languages
%description accel-ldso
This package contains an ld.so configured to run from /emul directory
}

%prep
%setup -n glibc-%{version} -q
# d7477af-to-8f08a7e.diff.gz
%patch0 -p1
cp %{SOURCE1001} .

%build
%{?asan:%gcc_unforce_options}
%{?hwasan:%gcc_unforce_options}

# Don't use as-needed, it breaks glibc assumptions
# Before enabling it, run the testsuite and verify that it
# passes completely
export LD_AS_NEEDED=0
#
# Default CFLAGS and Compiler
#
BuildFlags=$(echo %{optflags} | sed -e "s/-Wp,-D_FORTIFY_SOURCE=2//g" | sed -e "s/-ffast-math//" | sed -e "s/atom/i686/g" | sed -e "s/-fexceptions//" | sed -e "s/-fno-omit-frame-pointer//" | sed -e 's/-flto\(=[^[:space:]]\+\)\? //')
BuildFlags="$BuildFlags -O2 -g -U_FORTIFY_SOURCE"
BuildFlags="$(echo $BuildFlags | sed -e 's#-ffortify=[0-9]*##')"
BuildFlags="$(echo $BuildFlags | sed -e 's#-fstack-protector-strong##')"
BuildFlags="$(echo $BuildFlags | sed -e 's#-fstack-protector##')"
BuildFlags="$(echo $BuildFlags | sed -e 's/-Wa,-mimplicit-it=thumb\(-interwork\)\?//g' | sed -e 's/-mthumb\(-interwork\)\?//g')"
# Turn off all -Wformat enable flags as there are glibc tests that explicitly
# append -Wno-format and with enabled Wformat options that produced warnings
# that turns into errors. Remove -Wformat=1|2 or -Wformat-..-arg
BuildFlags="$(echo $BuildFlags | sed -re 's/-Wformat((=[1-2])|((-\w+)+))?(\s|$)//g')"

%ifarch %arm
# Support DA build with armv8 cpu in 32bit mode: prevent Werror on sqrt function
(echo ${BuildFlags} | grep '\-march=armv8') && BuildFlags="${BuildFlags} -Wno-error=unused-variable"
%endif
%ifarch %arm aarch64
# Glibc must have both functions' implementations
BuildFlags="$BuildFlags -U_LARGEFILE_SOURCE -U_LARGEFILE64_SOURCE -U_FILE_OFFSET_BITS"
%endif

#
# Build glibc
#
rm -rf "build"
mkdir "build"
pushd "build"

conf_cflags="$BuildFlags -funwind-tables -fPIC"
%{?asan: conf_cflags="$conf_cflags -DASAN_INIT_FIRST"}
%{?hwasan: conf_cflags="$conf_cflags -DASAN_INIT_FIRST -Wno-error=pragmas"}

function glibc_configure () {
  local aux_options=${@:1}

  CFLAGS="$conf_cflags" BUILD_CFLAGS="$conf_cflags" \
  CC="%{__cc}" CXX="%{__cxx}" \
  ../configure \
  --prefix=%{_prefix} \
  --libexecdir=%{_libexecdir} --infodir=%{_infodir} \
%ifarch riscv64
  --libdir=%{_libdir} \
%endif
  --enable-add-ons=",libidn" \
  %{?build_profile:--enable-profile} \
  --enable-kernel=%{enablekernel} \
  --enable-bind-now \
  --disable-nscd \
  --disable-experimental-malloc \
  libc_cv_cc_pie_default=yes \
%ifarch riscv64
  libc_cv_slibdir="/%{_lib}" \
  libc_cv_complocaledir="%{_prefix}/lib/locale" \
%endif
%ifnarch mipsel
  --enable-stackguard-randomization \
%endif
  --build=%{_build} --host=%{_host} \
%ifnarch %{ix86} x86_64
  --disable-multi-arch \
%endif
%ifarch %{ix86} x86_64
  --disable-mathvec \
%endif
  --enable-static-pie \
%if 0%{?asan}
  --disable-werror \
%endif
%if 0%{?dlconf}
  --enable-dlconf \
  --with-dlconf-ldconfig-dat-path=%{dlconf_ldconfig_dat_path} \
%endif
%if 0%{?dlconf_all_dirs}
  --enable-dlconf-all-dirs \
%endif
  ${aux_options}
}

glibc_configure
make %{?_smp_mflags}

#
# Build glibc_post_upgrade binary
#
%{__cc} \
    -static %{optflags} -Os \
    $RPM_SOURCE_DIR/glibc_post_upgrade.c -o glibc_post_upgrade \
    -L. -Bcsu \
    '-DREMOVE_TLS_DIRS' '-DREMOVE_PPC_OPTIMIZE_POWER5' \
    '-DLIBDIR="/%{_lib}"' '-DGCONV_MODULES_DIR="%{_libdir}/gconv"'

popd

# Prepare directory for qemu-accel ld.so
%{?build_qemu_accel_ld_so:
  mkdir "qemu-accel-ldso"
  pushd "qemu-accel-ldso"

  echo -e "# Begin configparms\nslibdir=%{emul_path}%{_libdir}\nsysconfdir=%{emul_path}%{_sysconfdir}\n# End configparms" > configparms
  glibc_configure --sysconfdir=%{emul_path}%{_sysconfdir} libc_cv_slibdir=%{emul_path}%{_libdir} libc_cv_sysconfdir=%{emul_path}%{_sysconfdir}
  make %{?_smp_mflags}

  popd
}

#
# Build html documentation
#
%if %{build_html}
make %{?_smp_mflags} -C "build" html
%endif

#
# Build ASan version of glibc
#
%{?asan:
%ifarch %{asan_arch}
configure_flags="--prefix=/usr --without-cvs --without-selinux --enable-stackguard-randomization --disable-mathvec"
configure_flags="$configure_flags --disable-sanity-checks"

GLIBC=%{_builddir}/%{name}-%{version}
ASAN_BUILD=$GLIBC/asan-build
unset CXXFLAGS
unset CFLAGS
unset LDFLAGS
%ifarch %{arm} aarch64
# Glibc must have both functions' implementations
CPPFLAGS="-U_LARGEFILE_SOURCE -U_LARGEFILE64_SOURCE -U_FILE_OFFSET_BITS -U_TIME_BITS"
%endif
CPPFLAGS+=" -DASAN_INIT_FIRST"

# build static wrapper, because we don't want asan to intercept allocators
%{__cxx} -o gcc-wrapper gcc-wrapper.cc -O3 -funroll-loops -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-exceptions -static

rm -rf $ASAN_BUILD
mkdir -p $ASAN_BUILD
pushd $ASAN_BUILD

CPPFLAGS=$CPPFLAGS \
	CC=$GLIBC/gcc-wrapper $GLIBC/configure $configure_flags

# Quick build - builds only libraries, but does not create symlinks.
make -r %{?_smp_mflags} -C $GLIBC objdir=`pwd` subdir_lib
# make -r %{?_smp_mflags} -C $GLIBC objdir=`pwd` install_root=$ASAN_INST install-lib
popd
%endif
}

%{?hwasan:
%ifarch %{hwasan_arch}
configure_flags="--prefix=/usr --without-cvs --without-selinux --enable-stackguard-randomization --disable-mathvec"
configure_flags="$configure_flags --disable-sanity-checks"

GLIBC=%{_builddir}/%{name}-%{version}
ASAN_BUILD=$GLIBC/hwasan-build
unset CXXFLAGS
unset CFLAGS
unset LDFLAGS
%ifarch %arm aarch64
# Glibc must have both functions' implementations
CPPFLAGS="-U_LARGEFILE_SOURCE -U_LARGEFILE64_SOURCE -U_FILE_OFFSET_BITS -U_TIME_BITS"
%endif
CPPFLAGS+=" -DASAN_INIT_FIRST"

# build static wrapper, because we don't want asan to intercept allocators
%{__cxx} -o gcc-wrapper gcc-wrapper.cc -O3 -funroll-loops -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-exceptions -static -DHWASAN_BUILD

rm -rf $ASAN_BUILD
mkdir -p $ASAN_BUILD
pushd $ASAN_BUILD

CPPFLAGS=$CPPFLAGS \
	CC=$GLIBC/gcc-wrapper $GLIBC/configure $configure_flags

# Quick build - builds only libraries, but does not create symlinks.
make -r %{?_smp_mflags} -C $GLIBC objdir=`pwd` subdir_lib
# make -r %{?_smp_mflags} -C $GLIBC objdir=`pwd` install_root=$ASAN_INST install-lib
popd
%endif
}

#######################################################################
###
### INSTALL
###
#######################################################################

%install
%{?build_tests:
	mkdir -p %{buildroot}/%{_builddir}

	install -m 0755 -t build %{_rpmconfigdir}/tizen/run_toolchain_tests.sh
	sed "s/^PROJECT_NAME=@PROJECT_NAME@$/PROJECT_NAME=%{name}/g" -i build/run_toolchain_tests.sh
	sed "s/^VERSION=@VERSION@$/VERSION=%{version}/g" -i build/run_toolchain_tests.sh
	sed "s/^RELEASE=@RELEASE@$/RELEASE=%{release}/g" -i build/run_toolchain_tests.sh
	sed "s/^ARCH=@ARCH@$/ARCH=%{_arch}/g" -i build/run_toolchain_tests.sh

	tar c -C %{_builddir} %{name}-%{version} | xz -3 > \
		%{buildroot}/%{_builddir}/%{name}-%{version}.tar.xz
}

# We don't want to strip the .symtab from our libraries in find-debuginfo.sh,
# certainly not from libpthread.so.* because it is used by libthread_db to find
# some non-exported symbols in order to detect if threading support
# should be enabled.  These symbols are _not_ exported, and we can't easily
# export them retroactively without changing the ABI.  So we have to
# continue to "export" them via .symtab, instead of .dynsym :-(
# But we also want to keep .symtab and .strtab of other libraries since some
# debugging tools currently require these sections directly inside the main
# files - specifically valgrind and PurifyPlus.
export STRIP_KEEP_SYMTAB=*.so*

# Make sure we will create the gconv-modules.cache
mkdir -p %{buildroot}%{_libdir}/gconv
touch %{buildroot}%{_libdir}/gconv/gconv-modules.cache

# Install base glibc
make %{?_smp_mflags} install_root=%{buildroot} install -C build

# Generate minimal en_US.UTF-8 locale (needed for BSD tar UTF-8 support)
# This is always installed regardless of build_locales setting to ensure
# UTF-8 locale support in the base build environment.
mkdir -p %{buildroot}/usr/lib/locale
pushd build
I18NPATH=../localedata GCONV_PATH=./iconvdata LC_ALL=C \
  ./locale/localedef --alias-file=../intl/locale.alias \
  -i en_US -f UTF-8 \
  --no-archive --prefix=%{buildroot} en_US.UTF-8
popd

# Install locales
%if %{build_locales}
# XXX Do not install locales in parallel!
pushd build
# localedef creates hardlinks to other locales if possible
# this will not work if we generate them in parallel.
# thus we need to run fdupes on  /usr/lib/locale/
# Still, on my system this is a speed advantage:
# non-parallel build for install-locales: 9:34mins
# parallel build with fdupes: 7:08mins
make %{?_smp_mflags} install_root=%{buildroot} localedata/install-locales
%fdupes %{buildroot}/usr/lib/locale
popd
%endif

# Create file list for glibc-locale package
%{find_lang} libc

# Prepare obsolete/, used only on some architectures:
export RPM_BUILD_ROOT
%ifarch %ix86
mkdir -p %{buildroot}/%{_lib}/obsolete
%endif

# Prepare symlinks to versioned libraries
ln -sf ../../%{_lib}/libpthread.so.0 %{buildroot}%{_libdir}/libpthread.so
ln -sf ../../%{_lib}/libutil.so.1 %{buildroot}%{_libdir}/libutil.so
ln -sf ../../%{_lib}/librt.so.1 %{buildroot}%{_libdir}/librt.so
ln -sf ../../%{_lib}/libdl.so.2 %{buildroot}%{_libdir}/libdl.so
ln -sf ../../%{_lib}/libm.so.6 %{buildroot}%{_libdir}/libm.so
ln -sf ../../%{_lib}/libresolv.so.2 %{buildroot}%{_libdir}/libresolv.so
ln -sf ../../%{_lib}/libnss_dns.so.2 %{buildroot}%{_libdir}/libnss_dns.so
ln -sf ../../%{_lib}/libnss_files.so.2 %{buildroot}%{_libdir}/libnss_files.so

# Miscelanna:

install -m 0700 build/glibc_post_upgrade %{buildroot}%{_sbindir}

install -m 644 %{SOURCE7} %{buildroot}/etc
install -m 644 %{SOURCE5} %{buildroot}/etc
install -m 644 posix/gai.conf %{buildroot}/etc

mkdir -p %{buildroot}/etc/default

%if %{build_html}
mkdir -p %{buildroot}%{_datadir}/doc/glibc
cp -p build/manual/libc/*.html %{buildroot}%{_datadir}/doc/glibc
%endif

#
# Create ld.so.conf
#
cat > %{buildroot}/etc/ld.so.conf <<EOF
%if "%{_lib}" == "lib64"
/usr/local/lib64
%endif
/usr/local/lib
include /etc/ld.so.conf.d/*.conf
# /lib64, /lib, /usr/lib64 and /usr/lib gets added
# automatically by ldconfig after parsing this file.
# So, they do not need to be listed.
EOF
# Add ldconfig cache directory for directory ownership
mkdir -p %{buildroot}/var/cache/ldconfig
# Empty the ld.so.cache:
rm -f %{buildroot}/etc/ld.so.cache
touch %{buildroot}/etc/ld.so.cache

# Don't look at ldd! We don't wish a /bin/sh requires
chmod 644 %{buildroot}%{_bindir}/ldd

# Remove timezone data, now coming in standalone package:
for i in sbin/sln usr/bin/tzselect usr/sbin/zic usr/bin/zdump etc/localtime; do
	rm -f %{buildroot}/$i
done
rm -rf %{buildroot}%{_datadir}/zoneinfo

%ifarch armv7hl
# Provide compatibility link
ln -s ld-linux-armhf.so.3 %{buildroot}/lib/ld-linux.so.3
%endif

%ifarch %ix86
# Provide compatibility link
ln -s ld-linux.so.2 %{buildroot}/lib/ld-linux.so
%endif

%ifarch riscv64
# Provide compatibility link
mkdir %{buildroot}/lib/
ln -s %{_libdir}/ld-linux-riscv64-lp64d.so.1 %{buildroot}/lib/ld-linux-riscv64-lp64d.so.1
%endif

%ifarch aarch64
# Provide compatibility link
mkdir %{buildroot}/lib
ln -s /lib64/ld-linux-aarch64.so.1 %{buildroot}/lib/ld-linux-aarch64.so.1
%endif

# Move getconf to %{_libexecdir}/getconf/ to avoid cross device link
mv %{buildroot}%{_bindir}/getconf %{buildroot}%{_libexecdir}/getconf/getconf
ln -s %{_libexecdir}/getconf/getconf %{buildroot}%{_bindir}/getconf

#######################################################################
###
### ...
###
#######################################################################

%{?asan:
%ifarch %{asan_arch}
HERE=%{_builddir}/%{name}-%{version}
GLIBC=$HERE
ASAN_BUILD=$HERE/asan-build
cp $ASAN_BUILD/libc.so %{buildroot}/%{_lib}/libc-%{version}-asan.so
%endif
}

%{?hwasan:
%ifarch %{hwasan_arch}
HERE=%{_builddir}/%{name}-%{version}
GLIBC=$HERE
ASAN_BUILD=$HERE/hwasan-build
cp $ASAN_BUILD/libc.so %{buildroot}/%{_lib}/libc-%{version}-hwasan.so
%endif
}

%{?build_qemu_accel_ld_so:
  pushd qemu-accel-ldso
  make -C ../elf objdir=`pwd` install_root=%{buildroot} ldso_install
  popd
}
%if 0%{?dlconf}
mkdir -p %{buildroot}/usr/lib/systemd/system/local-fs.target.wants/
cp %{SOURCE999} %{buildroot}/usr/lib/systemd/system/
ln -s ../$(basename %{SOURCE999}) %{buildroot}/usr/lib/systemd/system/local-fs.target.wants/
%endif

#######################################################################
###
### CHECK
###
#######################################################################

%check
# The testsuite will fail if asneeded is used
export LD_AS_NEEDED=0
# This has to pass on all platforms!
# Exceptions:
# None!
make %{?_smp_mflags} -k -C build check-abi

%files
%manifest %{name}.manifest
# glibc
%defattr(-,root,root)
%license LICENSES COPYING COPYING.LIB
%config(noreplace) /etc/bindresvport.blacklist
%config /etc/ld.so.conf
%attr(0644,root,root) %verify(not md5 size mtime) %ghost %config(missingok,noreplace) /etc/ld.so.cache
%config(noreplace) /etc/rpc
%verify(not md5 size mtime) %config(noreplace) /etc/nsswitch.conf
%verify(not md5 size mtime) %config(noreplace) /etc/gai.conf
%if 0%{?dlconf}
%attr(0644,root,root) /usr/lib/systemd/system/dlconf.service
%attr(0644,root,root) /usr/lib/systemd/system/local-fs.target.wants/dlconf.service
%endif

# Each architecture has a different name for the dynamic linker:
%ifarch %arm
%ifarch armv7hl
/lib/ld-linux-armhf.so.3
%endif
# Keep as compatibility link for armv7lh
/lib/ld-linux.so.3
%endif
%ifarch x86_64
/lib64/ld-linux-x86-64.so.2
%endif
%ifarch %ix86 %sparc
/lib/ld-linux.so.2
%endif
%ifarch %ix86
/lib/ld-linux.so
%endif
%ifarch aarch64
/%{_lib}/ld-linux-aarch64.so.1
/lib/ld-linux-aarch64.so.1
%endif
%ifarch riscv64
/lib64/ld-linux-riscv64-lp64d.so.1
/lib/ld-linux-riscv64-lp64d.so.1
%endif

/%{_lib}/libanl.so.1
/%{_lib}/libc.so*
/%{_lib}/libdl.so*
/%{_lib}/libm.so*
%ifarch aarch64
/%{_lib}/libmvec.so*
%endif
/%{_lib}/libnsl.so.1
/%{_lib}/libnss_compat.so.2
/%{_lib}/libnss_db.so.2
/%{_lib}/libnss_dns.so.2
/%{_lib}/libnss_files.so.2
/%{_lib}/libnss_optfiles.so.2
/%{_lib}/libnss_hesiod.so.2
/%{_lib}/libpthread.so*
/%{_lib}/libthread_db.so.1
/%{_lib}/libresolv.so.2
/%{_lib}/librt.so*
/%{_lib}/libutil.so*
/%{_lib}/libc_malloc_debug.so.0
%define optimized_libs() \
	%dir %attr(0755,root,root) /%{_lib}/%1\
	/%{_lib}/%1/libc.so.6*\
	/%{_lib}/%1/libm.so.6*\
	/%{_lib}/%1/libpthread.so*\
	/%{_lib}/%1/librt.so.1\
	/%{_lib}/%1/libthread_db.so.1

%dir %attr(0700,root,root) /var/cache/ldconfig
/sbin/ldconfig
%{_bindir}/ld.so
%{_bindir}/gencat
%{_bindir}/getconf
%{_bindir}/getent
%{_bindir}/iconv
%attr(755,root,root) %{_bindir}/ldd
%{_bindir}/locale
%{_bindir}/localedef
%dir %attr(0755,root,root) %{_libexecdir}/getconf
%{_libexecdir}/getconf/*
%{_sbindir}/glibc_post_upgrade
%{_sbindir}/iconvconfig
/%{_lib}/libBrokenLocale.so.1

# Minimal UTF-8 locale for BSD tar and other tools requiring UTF-8 support
# Note: /usr/lib/locale is owned by the filesystem package.
# tizen-locale package also installs locales under /usr/lib/locale/
# and needs to be updated to %exclude en_US.utf8 to avoid file conflict.
/usr/lib/locale/en_US.utf8

%ifarch %ix86

%files obsolete
%manifest %{name}.manifest
%license COPYING.LIB
%defattr (755,root,root,755)
%dir /%{_lib}/obsolete/
	# %dir /{_lib}/obsolete/noversion
	# /{_lib}/obsolete/noversion/libNoVersion.so.1
%endif

%files locale -f libc.lang
%manifest %{name}.manifest
%license COPYING COPYING.LIB
%defattr(-,root,root)
%{_datadir}/locale/locale.alias
%if %{build_locales}
%exclude /usr/lib/locale/en_US.utf8
%exclude /usr/lib/locale/en_US.UTF-8
/usr/lib/locale/*
%endif
%{_libdir}/gconv

%{?asan:
%ifarch %{asan_arch}
%files asan
%manifest %{name}.manifest
/%{_lib}/libc-%{version}-asan.so
%endif
}

%{?hwasan:
%ifarch %{hwasan_arch}
%files hwasan
%manifest %{name}.manifest
/%{_lib}/libc-%{version}-hwasan.so
%endif
}

%files devel
%manifest %{name}.manifest
%defattr(-,root,root)
%license COPYING COPYING.LIB
%doc NEWS README
%{_includedir}/*
%{_libdir}/*.o
%{_libdir}/*.so
# These static libraries are needed even for shared builds
%{_libdir}/libc_nonshared.a
%{_libdir}/libg.a
%ifarch ppc ppc64 s390 s390x sparc sparcv8 sparcv9 sparcv9v
# This is not built on sparc64.
	%{_libdir}/libnldbl_nonshared.a
%endif
%{_libdir}/libmcheck.a

%files devel-static
%manifest %{name}.manifest
%defattr(-,root,root)
%{_libdir}/libBrokenLocale.a
%{_libdir}/libanl.a
%{_libdir}/libc.a
%{_libdir}/libdl.a
%{_libdir}/libm.a
%ifarch aarch64
%{_libdir}/libm*.a
%{_libdir}/libmvec.a
%{_libdir}/libmvec_p.a
%endif
%{_libdir}/libpthread.a
%{_libdir}/libresolv.a
%{_libdir}/librt.a
%{_libdir}/libutil.a

%files info
%manifest %{name}.manifest
%defattr(-,root,root)
%doc %{_infodir}/libc.info.gz
%doc %{_infodir}/libc.info-?.gz
%doc %{_infodir}/libc.info-??.gz

%if %{build_html}
%files html
%manifest %{name}.manifest
%defattr(-,root,root)
%doc %{_prefix}/share/doc/glibc
%endif

%files i18ndata
%manifest %{name}.manifest
%defattr(-,root,root)
%{_prefix}/share/i18n

%if %{build_profile}
%files profile
%manifest %{name}.manifest
%license COPYING COPYING.LIB
%defattr(-,root,root)
%{_libdir}/libc_p.a
%{_libdir}/libBrokenLocale_p.a
%{_libdir}/libanl_p.a
%{_libdir}/libm_p.a
%{_libdir}/libpthread_p.a
%{_libdir}/libresolv_p.a
%{_libdir}/librt_p.a
%{_libdir}/libutil_p.a
%{_libdir}/libdl_p.a
%endif

%files devel-utils
%manifest %{name}.manifest
%defattr(-,root,root)
/%{_lib}/libmemusage.so
/%{_lib}/libpcprofile.so
/%{_libdir}/libBrokenLocale.so
/%{_lib}/libthread_db.so.1
/%{_libdir}/libthread_db.so
%dir /%{_libdir}/audit
/%{_libdir}/audit/sotruss-lib.so
# These need gd-devel for building
# %%{_bindir}/memusage
# %%{_bindir}/memusagestat
%{_bindir}/mtrace
%{_bindir}/pcprofiledump
%{_bindir}/sotruss
%{_bindir}/xtrace
%{_bindir}/pldd
%{_bindir}/sprof

%files extra
%manifest %{name}.manifest
%license COPYING.LIB
%defattr(-,root,root)
%{_bindir}/makedb
/var/db/Makefile

%{?build_tests:
%files tests
%defattr(-,root,root)
%{_builddir}/%{name}-%{version}.tar.xz
}

%{?build_qemu_accel_ld_so:
%files accel-ldso
%manifest glibc.manifest
%{emul_path}
}

%docs_package
%changelog
* Tue Sep  9 2014 Chanho Park <chanho61.park@samsung.com> upstream/2.20-26-g1a827dc
- Update to 2.20
* Tue Oct 15 2013 Jacek Bukarewicz <j.bukarewicz@samsung.com> accepted/tizen/20130912.200215@1ee152e
- Subpackage reorganization - devel-utils package
* Mon Aug 26 2013 Anas Nashif <anas.nashif@intel.com> glibc-2.18@e8510fa
- Update to 2.18
* Thu Aug  1 2013 Anas Nashif <anas.nashif@intel.com> submit/tizen/20130711.122834@23f8266
- Update package groups
* Mon Jul  8 2013 Junfeng Dong <junfeng.dong@intel.com> accepted/tizen/20130520.095530@99d0fc1
- No ld-linux-armhf.so.3 on armv7l architecture.
* Fri Mar 22 2013 Anas Nashif <anas.nashif@intel.com> submit/trunk/20130115.205551@642c22b
- Fixed package groups
* Tue Jan 15 2013 Anas Nashif <anas.nashif@intel.com> submit/trunk/20130114.165606@6013fa6
- do not provide /usr/lib/locale
* Mon Jan 14 2013 Anas Nashif <anas.nashif@intel.com> glibc-2.17@fe086f2
- Update to 2.17
