[general]
profile = profile.tizen_base_standard
buildroot = /home/toolchain/development/libc++_replacement/tmp/GBS-ROOT/BUILD-W2C-default

[profile.tizen_base_standard]
repos = repo.local-bcc, repo.base-standard, repo.libcxx-devel-support
buildconf = /home/toolchain/development/libc++_replacement/codes/qb/TIZEN/Tizen/Tizen-Base-Toolchain/project_config

[repo.local-bcc]
url = /home/toolchain/development/libc++_replacement/tmp/BUILD_W2C_0915/bcc-gcc-repo/

[repo.base-standard]
url = https://download.tizen.org/snapshots/TIZEN/Tizen/Tizen-Base-Toolchain/reference/repos/standard/packages/

[repo.libcxx-devel-support]
url = /home/toolchain/development/libc++_replacement/tmp/BUILD_W2_0912/gcc-support-repo/
