#!/usr/bin/env bash
set -euo pipefail

sdb=/home/toolchain/.local/bin/sdb
serial=192.168.108.26:26101
remote=/var/tmp/w2_r62_20260821
archive=/opt/usr/home/owner/share/tmp/w2-r62-payload.tar

command="set +e; shell_pid=\$\$; shell_ppid=\$PPID; echo SHELL_PID=\$shell_pid SHELL_PPID=\$shell_ppid; echo BEFORE_PROCESSES; ps -ef | awk -v self=\$shell_pid -v parent=\$shell_ppid '\$2 != self && \$2 != parent && \$0 ~ /w2_r62|r61_fixed|r61_reference|m2_fixed|m2_reference|m1_concurrency|facility_(fixed|reference)|async_(fixed|reference)|noncancel_(fixed|reference)|normal_(fixed|reference)/ && \$0 !~ /awk/ {print}'; before_rc=\$?; echo BEFORE_PROCESS_SCAN_EXIT=\$before_rc; for pattern in '$remote' r61_fixed r61_reference m2_fixed m2_reference m1_concurrency_fixed m1_concurrency_reference facility_fixed facility_reference async_fixed async_reference noncancel_fixed noncancel_reference normal_fixed normal_reference; do pids=\$(ps -ef | awk -v p=\"\$pattern\" -v self=\$shell_pid -v parent=\$shell_ppid 'index(\$0,p) && \$2 != self && \$2 != parent && \$0 !~ /awk/ {print \$2}'); if [ -n \"\$pids\" ]; then echo TERMINATING_PATTERN=\$pattern PIDS=\$pids; kill -TERM \$pids 2>/dev/null; fi; done; sleep 1; for pattern in '$remote' r61_fixed r61_reference m2_fixed m2_reference m1_concurrency_fixed m1_concurrency_reference facility_fixed facility_reference async_fixed async_reference noncancel_fixed noncancel_reference normal_fixed normal_reference; do pids=\$(ps -ef | awk -v p=\"\$pattern\" -v self=\$shell_pid -v parent=\$shell_ppid 'index(\$0,p) && \$2 != self && \$2 != parent && \$0 !~ /awk/ {print \$2}'); if [ -n \"\$pids\" ]; then echo KILLING_PATTERN=\$pattern PIDS=\$pids; kill -KILL \$pids 2>/dev/null; fi; done; rm -rf '$remote'; remote_rm_rc=\$?; rm -f '$archive'; archive_rm_rc=\$?; echo REMOTE_REMOVE_EXIT=\$remote_rm_rc; echo ARCHIVE_REMOVE_EXIT=\$archive_rm_rc; echo AFTER_PATHS; for path in '$remote' '$archive'; do if [ -e \"\$path\" ]; then echo PRESENT=\$path; else echo ABSENT=\$path; fi; done; echo AFTER_PROCESSES; remaining=\$(ps -ef | awk -v self=\$shell_pid -v parent=\$shell_ppid '\$2 != self && \$2 != parent && \$0 ~ /w2_r62|r61_fixed|r61_reference|m2_fixed|m2_reference|m1_concurrency|facility_(fixed|reference)|async_(fixed|reference)|noncancel_(fixed|reference)|normal_(fixed|reference)/ && \$0 !~ /awk/ {print}'); if [ -n \"\$remaining\" ]; then printf '%s\\n' \"\$remaining\"; after_rc=1; else after_rc=0; fi; echo AFTER_PROCESS_SCAN_EXIT=\$after_rc; [ \$remote_rm_rc -eq 0 ] && [ \$archive_rm_rc -eq 0 ] && [ \$after_rc -eq 0 ]; exit \$?"

printf 'REMOTE_COMMAND=%s\n' "$command"
"$sdb" -s "$serial" shell "$command"
