/*
 * Copyright (c) 2015 Samsung Electronics Co., Ltd. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

enum app_cmd {
	APP_START = 0,

	APP_OPEN = 1,
	APP_RESUME = 2,
	APP_RESUME_BY_PID = 3,
	APP_TERM_BY_PID = 4,
	APP_TERM_BY_PID_WITHOUT_RESTART = 5,
	APP_RESULT = 6,
	APP_START_RES = 7,
	APP_CANCEL = 8,
	APP_KILL_BY_PID = 9,
	APP_UPDATE_RUA_STAT = 10,

	APP_ADD_HISTORY = 11,
	APP_REMOVE_HISTORY = 12,
	APP_RUNNING_INFO = 13,
	APP_RUNNING_INFO_RESULT = 14,
	APP_IS_RUNNING = 15,
	APP_GET_APPID_BYPID = 16,
	APP_GET_PKGID_BYPID = 17,
	APP_GET_INFO_OK = 18,
	APP_GET_INFO_ERROR = 19,
	APP_KEY_EVENT = 20,  /**< Unused */

	APP_KEY_RESERVE = 21,  /**< Unused */
	APP_KEY_RELEASE = 22,  /**< Unused */
	APP_STATUS_UPDATE = 23,
	APP_RUNNING_LIST_UPDATE = 24,
	APP_TERM_REQ_BY_PID = 25,
	APP_TERM_BY_PID_ASYNC = 26,
	APP_TERM_BGAPP_BY_PID = 27,
	APP_PAUSE = 28,
	APP_PAUSE_BY_PID = 29,
	APP_GROUP_GET_WINDOW = 30,

	APP_GROUP_SET_WINDOW = 31,
	APP_GROUP_GET_FG = 32,
	APP_GROUP_GET_LEADER_PID = 33,
	APP_GROUP_GET_LEADER_PIDS = 34,
	APP_GROUP_GET_GROUP_PIDS = 35,
	APP_GROUP_GET_IDLE_PIDS = 36,
	APP_GROUP_LOWER = 37,
	APP_GROUP_CLEAR_TOP = 38,
	APP_GROUP_ACTIVATE_BELOW = 39,
	APP_GET_STATUS = 40,

	APP_ADD_LOADER = 41,
	APP_REMOVE_LOADER = 42,
	APP_GET_PID = 43,
	APP_GET_DC_SOCKET_PAIR = 44,
	APP_GET_MP_SOCKET_PAIR = 45,
	APP_COM_CREATE = 46,
	APP_COM_JOIN = 47,
	APP_COM_SEND = 48,
	APP_COM_LEAVE = 49,
	APP_COM_MESSAGE = 50,

	WIDGET_ADD = 51,
	WIDGET_DEL = 52,
	WIDGET_LIST = 53,
	WIDGET_UPDATE = 54,
	WIDGET_COUNT = 55,
	WIDGET_GET_CONTENT = 56,
	APP_REGISTER_PID = 57,
	APP_WAKE = 58,
	APP_SUSPEND = 59,
	AMD_RELOAD_APPINFO = 60,

	LAUNCHPAD_DEAD_SIGNAL = 61,
	APP_ALL_RUNNING_INFO = 62,
	APP_SET_APP_CONTROL_DEFAULT_APP = 63,
	APP_UNSET_APP_CONTROL_DEFAULT_APP = 64,
	APP_START_ASYNC = 65,
	APP_SET_PROCESS_GROUP = 66,
	APP_PREPARE_CANDIDATE_PROCESS = 67,
	APP_TERM_BY_PID_SYNC = 68,
	APP_GET_STATUS_BY_APPID = 69,
	APP_GET_LAST_CALLER_PID = 70,

	APP_TERM_BY_PID_SYNC_WITHOUT_RESTART = 71,
	APP_RESUME_BY_PID_ASYNC = 72,
	APP_SET_ALIAS_APPID = 73,
	APP_UNSET_ALIAS_APPID = 74,
	APP_ENABLE_ALIAS_INFO = 75,
	APP_DISABLE_ALIAS_INFO = 76,
	APP_GROUP_ACTIVATE_ABOVE = 77,
	ADD_APP_SCREEN = 78,
	REMOVE_APP_SCREEN = 79,
	APP_UPDATE_REQUESTED = 80,

	ADD_SCREEN_VIEWER = 81,
	REMOVE_SCREEN_VIEWER = 82,
	LAUNCHPAD_LAUNCH_SIGNAL = 83,
	APP_RUNNING_INSTANCE_INFO = 84,
	APP_GET_INSTANCE_ID_BYPID = 85,
	APP_SET_CACHE = 86,
	APP_GET_APPID_FROM_CACHE = 87,
	APP_INVALIDATE_CACHE = 88,
	APP_STARTUP_SIGNAL = 89,
	APP_WINDOW_ATTACH = 90,

	APP_WINDOW_DETACH = 91,
	APP_START_RES_ASYNC = 92,
	APP_NOTIFY_EXIT = 93,
	APP_GET_APPID_BY_SURFACE_ID = 94,
	APP_GET_INSTANCE_ID_BY_SURFACE_ID = 95,
	UPDATE_SCREEN_VIEWER_STATUS = 96,
	WIDGET_RUNNING_INFO = 97,
	JOB_STATUS_UPDATE = 98,
	WIDGET_CHANGE_STATUS = 99,
	RPC_PORT_PREPARE_STUB = 100,

	RPC_PORT_CREATE_SOCKET_PAIR = 101,
	RPC_PORT_NOTIFY_RPC_FINISHED = 102,
	COMPLICATION_UPDATE_REQUEST = 103,
	APP_NOTIFY_START = 104,
	WATCHDOG_ENABLE = 105,
	WATCHDOG_DISABLE = 106,
	WATCHDOG_PING = 107,
	WATCHDOG_KICK = 108,
	APP_SEND_LAUNCH_REQUEST = 109,
	APP_SEND_LAUNCH_REQUEST_SYNC = 110,

	COMP_NOTIFY_START = 111,
	COMP_NOTIFY_EXIT = 112,
	COMP_STATUS_UPDATE = 113,
	APP_TERM_INSTANCE_ASYNC = 114,
	APP_GROUP_SET_WINDOW_V2 = 115,
	APP_GROUP_LOWER_V2 = 116,
	APP_GROUP_GET_LEADER_IDS = 117,
	APP_GROUP_GET_GROUP_INFO = 118,
	APP_GROUP_GET_IDLE_INFO = 119,
	COMP_CONTEXT_FOREACH = 120,

	COMP_CONTEXT_GET = 121,
	COMP_CONTEXT_IS_RUNNING = 122,
	COMP_CONTEXT_RESUME = 123,
	COMP_CONTEXT_PAUSE = 124,
	COMP_CONTEXT_TERMINATE_BG_COMP = 125,
	COMP_CONTEXT_TERMINATE = 126,
	APP_RESUME_INSTANCE = 127,
	APP_PAUSE_INSTANCE = 128,
	APP_TERM_BG_INSTANCE = 129,
	LAUNCHPAD_CHILD_PROCESS = 130, /* unused */

	COMP_INFO_GET = 131,
	COMP_INFO_FOREACH = 132,
	APP_TERMINATE = 133,
	APP_IS_RUNNING_V2 = 134,
	ANR_NOTIFY = 135,
	APP_GET_RUNNING_CONTEXT = 136,
	LAUNCHER_SERVICE_NOTIFY_ANIMATION_STARTED = 137,
	LAUNCHER_SERVICE_NOTIFY_ANIMATION_FINISHED = 138,
	APP_SEND_RESUME_REQUEST = 139,
	APP_PREPARE_APP_DEFINED_LOADER = 140,

	WIDGET_DISABLE = 141,
	TRIGGER_APP_SCREEN_FOCUSED_FORCE = 142,
	WIDGET_EVENT = 143,
	SET_PRIVATE_SHARING = 144,
	UNSET_PRIVATE_SHARING = 145,
	APP_CONTEXT_GET = 146,
	APP_CONTEXT_GET_BY_INSTANCE_ID = 147,
	APP_CONTEXT_GET_BY_PID = 148,
	APP_GROUP_ADD = 149,
	APP_GROUP_REMOVE = 150,

	APP_GET_APPID_LIST = 151,
	COMP_PORT_EXIST = 152,
	COMP_PORT_CREATE = 153,
	COMP_PORT_DESTROY = 154,
	APP_LIFECYCLE_UPDATE_STATE = 155,

	APP_STATUS_UPDATE_V2 = 156,
	APP_GET_APP_CONTROL_DEFAULT_APPS = 157,
	APP_GET_APPID_BY_ALIAS_APPID = 158,
	APP_GET_APP_CONTROL_DEFAULT_APP = 159,
	APP_LIFECYCLE_GET_STATE = 160,

	PROC_REGISTER = 161,
	PROC_DEREGISTER = 162,
	PROC_GET_NAME = 163,
	PROC_GET_EXTRA = 164,
	RPC_PORT_CREATE = 165,

	RPC_PORT_DESTROY = 166,
	RPC_PORT_EXIST = 167,
	APP_WINDOW_ATTACH_BELOW = 168,
	PROC_GROUP_ADD = 169,
	PROC_GROUP_REMOVE = 170,

	APP_CONNECT = 171,
	APP_SET_AUTO_RESTART = 172,
	BOOT_SEQUENCE_START_APP = 173,
	BOOT_SEQUENCE_GET_APPINFO_LIST = 174,
	BOOT_SEQUENCE_RELOAD = 175,

	PKG_PRE_EVENT_SEND = 176,
	PROC_GROUP_FOREACH = 177,
	PROC_GROUP_GET = 178,
	APP_THAW = 179,
	APP_TERM_BY_PID_FOR_OOM = 180,

	WATCHDOG_PRINT_BT = 181,
	APP_KILL_BY_PID_FOR_OOM = 182,
	APP_REMOUNT_SUBSESSION_PATH = 183,
	APP_REMOUNT_GADGET_PATH = 184,
	PKG_GET_INSTALL_STATUS = 185,

	TEAM_APP_RUN = 186,
	TEAM_APP_STOP = 187,
	TEAM_APP_INST_RUN = 188,
	TEAM_APP_INST_PRESTOP = 189,
	TEAM_APP_INST_POSTSTOP = 190,

	TEAM_APP_INST_UPDATE_STATE = 191,
	APP_GET_LAST_CALLER_PID_BY_APPID = 192,
	TEAM_APP_INST_GET_FOCUS = 193,
	APP_NOTIFY_OOM_KILL = 194,

	APP_CMD_MAX
};

const char *aul_cmd_convert_to_string(int cmd);

#ifdef __cplusplus
}
#endif
