#!/usr/bin/env bash
set -u

ROOT=/home/toolchain/development/libc++_replacement
R9="$ROOT/progress/R9"
LLVM="$ROOT/codes/llvm"

record() {
    local command="$1"
    printf 'COMMAND=%s\n' "$command"
    (cd "$ROOT" && bash -o pipefail -c "$command")
    local rc=$?
    printf 'EXIT_CODE=%d\n\n' "$rc"
    return 0
}

record "bash -n '$R9'/commands/*.sh"
record "for f in '$R9'/commands/0{1,2,3,4}_*.log; do printf '%s\\tCOMMANDS=' \"\$f\"; rg -c '^COMMAND=' \"\$f\"; printf 'EXIT_CODES='; rg -c '^EXIT_CODE=' \"\$f\"; done"
record "rg -n 'EXIT_CODE=[2-9]|No such file|Traceback|fatal:' '$R9'/commands/*.log || true"
record "git -C '$LLVM' branch --show-current && git -C '$LLVM' rev-parse HEAD && git -C '$LLVM' status --porcelain=v1"
record "test \"\$(git -C '$LLVM' branch --show-current)\" = tizen_base && test \"\$(git -C '$LLVM' rev-parse HEAD)\" = 3d3e3da49e00ae89b0ff928dee811d6d0d1d4f0b && test -z \"\$(git -C '$LLVM' status --porcelain=v1)\""
record "sha256sum '$R9/generated/srpm/0001-Apply-Tizen-toolchain-compatibility-fixes.patch' '$R9/generated/bdf_source_only_gbp_header_normalized.patch'"
record "cmp -s '$R9/generated/srpm/0001-Apply-Tizen-toolchain-compatibility-fixes.patch' '$R9/generated/bdf_source_only_gbp_header_normalized.patch'"
record "test \"\$(rpm2cpio '$ROOT/tmp/corpus/srpms/llvm-22.1.8-18.1.src.rpm' | cpio -i --to-stdout 'llvm-22.1.8.tar.gz' 2>/dev/null | sha256sum | awk '{print \$1}')\" = 16a932e1bad4e1ed68938b48aa9fe5613992426584a75dd17dacabf2151d122e"
record "rg -n '^record \"gbs export' '$R9'/commands/*.sh"
record "rg -n 'EXPORT_BASELINE_TAG_UPSTREAM_22.1.8|PATCH_AUTOGENERATED_CONFIRMED|PLATFORM_STYLE_PATCH_EXPORT_DETERMINED|0006-libcxxabi|本报告不含处置建议' '$R9/R9_report.md' '$R9'/*.tsv"
record "find '$R9' -type f ! -name evidence_manifest.tsv ! -name 05_validate_and_manifest.log -printf '%P\\0' | LC_ALL=C sort -z | while IFS= read -r -d '' f; do sha256sum \"$R9/\$f\" | awk -v rel=\"\$f\" '{print rel \"\\t\" \$1}'; done > '$R9/evidence_manifest.tsv'"
record "nl -ba '$R9/evidence_manifest.tsv'"
record "git status --short"
