#!/bin/bash
set -e
root=/home/toolchain/development/libc++_replacement/tmp/GBS-ROOT/R30-semantic-libcxx-armv7l-20260812-01/local/BUILD-ROOTS/scratch.armv7l.0
exec /usr/bin/qemu-arm-static -L "$root" "$root/usr/bin/ld" "$@"
