Name:           tensorflow2
VCS:            platform/upstream/tensorflow2#1cdba73549f741720f11dd53da1bb516b03763a2-dirty
Summary:        TensorFlow 2.x with Lite and XLA AOT support
Version:        2.18.0
Release:        1
License:        Apache-2.0
Source0:        %{name}-%{version}.tar.gz
Source1001:     tensorflow2.manifest
Source1002:     tensorflow2-lite.pc.in
Source1003:     tensorflow2-aot.pc.in

Source2000:     abseil-cpp.tar.gz
Source2001:     cpuinfo.tar.gz
Source2002:     egl_headers.tar.gz
Source2003:     eigen.tar.gz
Source2004:     farmhash.tar.gz
Source2005:     fft2d.tar.gz
Source2006:     flatbuffers.tar.gz
Source2007:     fp16.tar.gz
Source2008:     gemmlowp.tar.gz
Source2009:     ml_dtypes.tar.gz
Source2010:     neon2sse.tar.gz
Source2011:     opencl_headers.tar.gz
Source2012:     opengl_headers.tar.gz
Source2013:     protobuf.tar.gz
Source2014:     ruy.tar.gz
Source2015:     vulkan_headers.tar.gz
Source2016:     XNNPACK-cpuinfo.tar.gz
Source2017:     XNNPACK-FP16-psimd.tar.gz
Source2018:     XNNPACK-fp16.tar.gz
Source2019:     XNNPACK-fxdiv.tar.gz
Source2020:     XNNPACK-kleidiai.tar.gz
Source2021:     XNNPACK-pthreadpool.tar.gz
Source2022:     xnnpack.tar.gz

# AOT (Ahead-of-Time) compilation support for LLVM MLGO
# Generated by: scripts/extract_aot_components.sh
Source3000:     tensorflow2-aot.tar.gz

%define USE_CLANG     "ON"
%define USE_XNNPACK   "ON"
%define USE_OPENCL    "ON"
%define SHARED_LIB    "OFF"

# clang + armv7hl build fails
%ifarch armv7hl
%define USE_CLANG     "OFF"
%endif

# R105 validation-only switch. This is not part of the candidate package change;
# it makes the existing USE_CLANG=OFF branch reachable on the three matrix arches.
%if 0%{?r105_validation_force_gcc}
%define USE_CLANG     "OFF"
%endif

%if %{USE_CLANG} == "ON"
%if %{defined _toolchain}
%if %{toolchain_is clang}
%define build_with_libcxx 1
%endif
%endif
%endif

%if %{USE_CLANG} == "ON"
%ifarch armv7l
BuildRequires: python-accel-armv7l-cross-arm
BuildRequires: clang-accel-armv7l-cross-arm
%endif

%ifarch armv7hl
BuildRequires: python-accel-armv7hl-cross-arm
BuildRequires: clang-accel-armv7hl-cross-arm
%endif

%ifarch aarch64
BuildRequires: python-accel-aarch64-cross-aarch64
BuildRequires: clang-accel-aarch64-cross-aarch64
%endif

%ifarch riscv64
BuildRequires: python-accel-riscv64-cross-riscv64
BuildRequires: clang-accel-riscv64-cross-riscv64
%endif

BuildRequires: clang
%endif

BuildRequires: cmake
BuildRequires: ninja
BuildRequires: python3
%if 0%{?build_with_libcxx}
BuildRequires: libc++-devel
BuildRequires: libc++abi-devel
%endif

%description
This is a standalone package of TensorFlow Lite.
TensorFlow Lite is TensorFlow's lightweight solution for mobile and embedded devices. It enables low-latency inference of on-device machine learning models with a small binary size and fast performance supporting hardware acceleration.

See the documentation: https://www.tensorflow.org/lite/

%package lite-devel
Summary: TensorFlow Lite development headers and static library.

%description lite-devel
TensorFlow Lite development headers and static library.

%package lite-flatbuf-schema
Summary: TensorFlow Lite schema file
Requires: tensorflow2-lite-devel = %{version}-%{release}

%description lite-flatbuf-schema
TensorFlow Lite schema file

# %ifnarch
%package lite-util
Summary: TensorFlow Lite developer util

%description lite-util
It includes a executable to benchmark any tflite model
# %endif

%package aot-devel
Summary: TensorFlow XLA AOT compilation support for LLVM MLGO
Requires: tensorflow2-lite-devel = %{version}-%{release}
AutoReqProv: no

%description aot-devel
Headers, XLA runtime sources, and tools needed for LLVM MLGO AOT
(Ahead-of-Time) compilation. This package provides TENSORFLOW_AOT_PATH
support for building LLVM with embedded MLGO models.

%package -n libtensorflow2-aot-runtime
Summary: XLA AOT runtime static library for MLGO
AutoReqProv: no

%description -n libtensorflow2-aot-runtime
Static library built from xla_aot_runtime_src, needed to link
LLVM with MLGO AOT support.

%prep
%setup -q
cp %{SOURCE1001} .
mkdir -p externals
pushd externals
cp %{SOURCE2000} .
cp %{SOURCE2001} .
cp %{SOURCE2002} .
cp %{SOURCE2003} .
cp %{SOURCE2004} .
cp %{SOURCE2005} .
cp %{SOURCE2006} .
cp %{SOURCE2007} .
cp %{SOURCE2008} .
cp %{SOURCE2009} .
cp %{SOURCE2010} .
cp %{SOURCE2011} .
cp %{SOURCE2012} .
cp %{SOURCE2013} .
cp %{SOURCE2014} .
cp %{SOURCE2015} .
cp %{SOURCE2016} .
cp %{SOURCE2017} .
cp %{SOURCE2018} .
cp %{SOURCE2019} .
cp %{SOURCE2020} .
cp %{SOURCE2021} .
cp %{SOURCE2022} .
popd

# Extract AOT components for LLVM MLGO support
mkdir -p aot
pushd aot
tar xzf %{SOURCE3000}
popd

%build
mkdir -p build
pushd build

%if %{USE_CLANG} == "ON"
%define host_triplet %(echo %{_host} | sed 's/^i686-/i586-/')
CLANG_ASMFLAGS=" --target=%{host_triplet} "
CLANG_CFLAGS=" --target=%{host_triplet} "
CLANG_CXXFLAGS=" --target=%{host_triplet} "
%if 0%{?build_with_libcxx}
CLANG_CXXFLAGS="${CLANG_CXXFLAGS} -stdlib=libc++"
export LDFLAGS="${LDFLAGS} -stdlib=libc++ -Wl,--no-as-needed -lc++abi -Wl,--as-needed"
%endif

export ASMFLAGS="${CLANG_ASMFLAGS}"
export CFLAGS="${CLANG_CFLAGS}"
export CXXFLAGS="${CLANG_CXXFLAGS}"
%else # USE_CLANG OFF
%ifarch %arm aarch64
  EXTRA_CFLAGS="${EXTRA_CFLAGS} -funsafe-math-optimizations"
  EXTRA_CXXFLAGS="${EXTRA_CXXFLAGS} -funsafe-math-optimizations"
  %ifarch %arm
    EXTRA_CFLAGS="${EXTRA_CFLAGS} -mno-unaligned-access"
    EXTRA_CXXFLAGS="${EXTRA_CXXFLAGS} -mno-unaligned-access"
  %endif
  %ifarch armv7l
    EXTRA_CFLAGS="${EXTRA_CFLAGS} -mfloat-abi=softfp -march=armv7-a -mfpu=neon-vfpv4 -funsafe-math-optimizations -mfp16-format=ieee"
    EXTRA_CXXFLAGS="${EXTRA_CXXFLAGS} -mfloat-abi=softfp -march=armv7-a -mfpu=neon-vfpv4 -funsafe-math-optimizations -mfp16-format=ieee"
  %endif
  %ifarch armv7hl
    EXTRA_CFLAGS="${EXTRA_CFLAGS} -mfloat-abi=hard -march=armv7-a -mfpu=neon-vfpv4 -funsafe-math-optimizations -mfp16-format=ieee"
    EXTRA_CXXFLAGS="${EXTRA_CXXFLAGS} -mfloat-abi=hard -march=armv7-a -mfpu=neon-vfpv4 -funsafe-math-optimizations -mfp16-format=ieee"
  %endif
%endif

# VD/TV: Disable a link-time optimization (requested on 2020-06-09)
%if "%{?profile}" == "tv"
  EXTRA_CFLAGS="${EXTRA_CFLAGS} -fno-lto"
  EXTRA_CXXFLAGS="${EXTRA_CXXFLAGS} -fno-lto"
  %ifarch armv7l
    EXTRA_CFLAGS="${EXTRA_CFLAGS} -march=armv7-a -mtune=cortex-a8"
    EXTRA_CXXFLAGS="${EXTRA_CXXFLAGS} -march=armv7-a -mtune=cortex-a8"
    EXTRA_CFLAGS=${EXTRA_CFLAGS/-mcpu=cortex-a53/}
    EXTRA_CXXFLAGS=${EXTRA_CXXFLAGS/-mcpu=cortex-a53/}
  %endif
%endif
%endif # USE_CLANG

%if %{USE_CLANG} == "ON"
export CC=clang
export CXX=clang++
CC=clang CXX=clang++ \
cmake \
  -DCMAKE_C_COMPILER=clang \
  -DCMAKE_CXX_COMPILER=clang++ \
  -DCMAKE_VERBOSE_MAKEFILE=ON \
  -GNinja \
  -DTFLITE_BUILD_SHARED_LIB="%{SHARED_LIB}" \
  -DTFLITE_ENABLE_XNNPACK="%{USE_XNNPACK}" \
  -DTFLITE_ENABLE_GPU="%{USE_OPENCL}" \
  ../tensorflow/lite
%else # USE_CLANG OFF
cmake \
  -DCMAKE_VERBOSE_MAKEFILE=ON \
  -GNinja \
  -DCMAKE_C_FLAGS="${EXTRA_CFLAGS}" \
  -DCMAKE_CXX_FLAGS="${EXTRA_CXXFLAGS}" \
  -DTFLITE_BUILD_SHARED_LIB="%{SHARED_LIB}" \
  -DTFLITE_ENABLE_XNNPACK="%{USE_XNNPACK}" \
  -DXNNPACK_ENABLE_ARM_BF16=OFF \
  -DXNNPACK_ENABLE_ARM_I8MM=OFF \
  -DTFLITE_ENABLE_GPU="%{USE_OPENCL}" \
  ../tensorflow/lite
%endif # USE_CLANG

cmake --build . %{?_smp_mflags}

cmake --build . %{?_smp_mflags} -t benchmark_model

popd

# Build AOT runtime library (xla_aot_runtime_src)
# Use the same cross-compilation setup as TFLite build
mkdir -p build-aot
pushd build-aot

%if %{USE_CLANG} == "ON"
cmake \
  -DCMAKE_C_COMPILER=clang \
  -DCMAKE_CXX_COMPILER=clang++ \
  -DCMAKE_C_FLAGS="${CFLAGS}" \
  -DCMAKE_CXX_FLAGS="${CXXFLAGS}" \
  -DCMAKE_VERBOSE_MAKEFILE=ON \
  -GNinja \
  %{_builddir}/%{name}-%{version}/aot/xla_aot_runtime_src
%else
cmake \
  -DCMAKE_C_FLAGS="${EXTRA_CFLAGS}" \
  -DCMAKE_CXX_FLAGS="${EXTRA_CXXFLAGS}" \
  -DCMAKE_VERBOSE_MAKEFILE=ON \
  -GNinja \
  %{_builddir}/%{name}-%{version}/aot/xla_aot_runtime_src
%endif

ninja
popd

%install
mkdir -p %{buildroot}%{_libdir}
mkdir -p %{buildroot}%{_libdir}/pkgconfig
mkdir -p %{buildroot}%{_includedir}/tensorflow2/lite
mkdir -p %{buildroot}%{_includedir}/tensorflow2/compiler/mlir
mkdir -p %{buildroot}%{_bindir}
mkdir -p %{buildroot}%{_datadir}/tensorflow2/lite/schema
pushd %{buildroot}%{_includedir}/tensorflow2
ln -sf . %{buildroot}%{_includedir}/tensorflow2/tensorflow
# TF2Lite users do: #include <tensorflow/FILENAME.h>
popd

cp %{SOURCE1002} .
sed -i 's:@libdir@:%{_libdir}:g
    s:@includedir@:%{_includedir}/tensorflow2/:g' ./tensorflow2-lite.pc.in

# Put the generated files into the buildroot folder
## install built static library and benchmark binary
%if %{SHARED_LIB} == "ON"
  install -m 0644 ./build/libtensorflow-lite.so %{buildroot}%{_libdir}/libtensorflow2-lite.so
%else
  install -m 0644 ./build/libtensorflow-lite-bundled.a %{buildroot}%{_libdir}/libtensorflow2-lite.a
%endif

install -m 0655 ./build/tools/benchmark/benchmark_model %{buildroot}%{_bindir}/tflite_benchmark_model

## install headers
pushd tensorflow/lite
find . -name "*.h" -type f -exec cp --parents {} %{buildroot}%{_includedir}/tensorflow2/lite \;
popd

pushd tensorflow/compiler/mlir
find . -name "*.h" -type f -exec cp --parents {} %{buildroot}%{_includedir}/tensorflow2/compiler/mlir \;
popd

### rename tensorflow -> tensorflow2
pushd %{buildroot}%{_includedir}/tensorflow2/
for HEADER in `find -name '*.h'`; do
  sed -i 's|#\W*include\W*<tensorflow/|#include <tensorflow2/|' ${HEADER}
  sed -i 's|#\W*include\W*"tensorflow/|#include "tensorflow2/|' ${HEADER}
done
popd

## install flatbuffers header for tensorflow lite
mkdir -p %{buildroot}%{_includedir}/tensorflow2/flatbuffers
pushd build/flatbuffers/include
find . -name "*.h" -type f -exec cp --parents {} %{buildroot}%{_includedir}/tensorflow2/ \;
popd

## change flatbuffers header include path in tflite / flatbuffers
pushd %{buildroot}%{_includedir}/tensorflow2/
for HEADER in `find -name '*.h'`; do
  sed -i 's|#\W*include\W*<flatbuffers/|#include <tensorflow2/flatbuffers/|' ${HEADER}
  sed -i 's|#\W*include\W*"flatbuffers/|#include "tensorflow2/flatbuffers/|' ${HEADER}
done
popd

## install flatbuf schema
mkdir -p %{buildroot}%{_datadir}/tensorflow2/compiler/mlir/lite/schema
install -m 0644 tensorflow/compiler/mlir/lite/schema/schema.fbs %{buildroot}%{_datadir}/tensorflow2/compiler/mlir/lite/schema/schema.fbs

pushd %{buildroot}%{_datadir}/tensorflow2/lite/schema
ln -sf ../../compiler/mlir/lite/schema/schema.fbs ./
popd

## install pc file
install -m 0644 tensorflow2-lite.pc.in %{buildroot}%{_libdir}/pkgconfig/tensorflow2-lite.pc

## ========== AOT package installation ==========

# Install AOT headers (include/ from extracted tarball)
# Install to both %{_includedir} (for development) and %{_datadir} (for LLVM TENSORFLOW_AOT_PATH)
mkdir -p %{buildroot}%{_includedir}/tensorflow2/aot
cp -r aot/include %{buildroot}%{_includedir}/tensorflow2/aot/

# Install xla_aot_runtime_src and include/ to %{_datadir} (for LLVM TENSORFLOW_AOT_PATH)
# LLVM CMake uses TENSORFLOW_AOT_PATH=%{_datadir}/tensorflow2/aot and expects:
#   ${TENSORFLOW_AOT_PATH}/include/          — C++ headers for AOT compilation
#   ${TENSORFLOW_AOT_PATH}/xla_aot_runtime_src/ — XLA runtime source
mkdir -p %{buildroot}%{_datadir}/tensorflow2/aot
cp -r aot/xla_aot_runtime_src %{buildroot}%{_datadir}/tensorflow2/aot/
cp -r aot/include %{buildroot}%{_datadir}/tensorflow2/aot/

# Install saved_model_cli (AOT compiler tool)
# Note: saved_model_cli is a Python script; fix shebang to use system python3
if [ -f aot/bin/saved_model_cli ]; then
  mkdir -p %{buildroot}%{_datadir}/tensorflow2/aot/bin
  sed '1s|^#!.*python.*|#!/usr/bin/python3|' aot/bin/saved_model_cli > %{buildroot}%{_datadir}/tensorflow2/aot/bin/saved_model_cli
  chmod 0755 %{buildroot}%{_datadir}/tensorflow2/aot/bin/saved_model_cli
fi

# Install AOT runtime static library
install -m 0644 build-aot/libtf_xla_runtime.a %{buildroot}%{_libdir}/libtf_xla_runtime.a

# Install AOT pc file
cp %{SOURCE1003} .
sed -i 's:@libdir@:%{_libdir}:g
    s:@includedir@:%{_includedir}:g
    s:@aot_path@:%{_datadir}/tensorflow2/aot:g
    s:@VERSION@:%{version}:g
    s:@prefix@:%{_prefix}:g
    s:@exec_prefix@:%{_exec_prefix}:g' ./tensorflow2-aot.pc.in
install -m 0644 tensorflow2-aot.pc.in %{buildroot}%{_libdir}/pkgconfig/tensorflow2-aot.pc

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files lite-devel
%defattr(-,root,root,-)
%manifest tensorflow2.manifest
%license LICENSE
%if %{SHARED_LIB} == "ON"
  %{_libdir}/libtensorflow2-lite.so
%else
  %{_libdir}/libtensorflow2-lite.a
%endif
%{_libdir}/pkgconfig/tensorflow2-lite.pc
%{_includedir}/tensorflow2/compiler
%{_includedir}/tensorflow2/lite
%{_includedir}/tensorflow2/tensorflow
%{_includedir}/tensorflow2/flatbuffers

%files lite-flatbuf-schema
%{_datadir}/tensorflow2/compiler/mlir/lite/schema/schema.fbs
%{_datadir}/tensorflow2/lite/schema/schema.fbs

%files lite-util
%{_bindir}/tflite_benchmark_model

%files aot-devel
%defattr(-,root,root,-)
%{_includedir}/tensorflow2/aot/include
%{_datadir}/tensorflow2/aot/include
%{_datadir}/tensorflow2/aot/xla_aot_runtime_src
%{_datadir}/tensorflow2/aot/bin
%{_libdir}/pkgconfig/tensorflow2-aot.pc

%files -n libtensorflow2-aot-runtime
%defattr(-,root,root,-)
%{_libdir}/libtf_xla_runtime.a


%changelog
* Tue Jun 16 2026 Cline SR <cline-sr@samsung.com>
 - Add XLA AOT compilation support for LLVM MLGO
 - New subpackage: tensorflow2-aot-devel (AOT headers, sources, tools)
 - New subpackage: libtensorflow2-aot-runtime (AOT runtime static library)
 - Add Source3000: tensorflow2-aot.tar.gz
 - Add Source1003: tensorflow2-aot.pc.in

* Thu Dec 26 2024 Yongjoo Ahn <yongjoo1.ahn@samsung.com>
 - Initial package to use TensorFlow Lite v2.18.0
