import("//build/config/compiler/compiler.gni")
import("//tizen_src/build/config/tizen_features.gni")

declare_args() {
  package_id = "org.tizen.chromium-efl"
}

action("ewk_api_wrapper_source") {
  script = "ewk_api_wrapper_generator.py"
  sources = [
    "ewk_interface_main.h",
    "//tizen_src/ewk/efl_integration/public/EWebKit.h",
    "//tizen_src/ewk/efl_integration/public/EWebKit_internal.h",
    "//tizen_src/ewk/efl_integration/public/EWebKit_product.h",
    "//tizen_src/ewk/efl_integration/public/ewk_cookie_parser.h",
    "//tizen_src/ewk/efl_integration/public/ewk_media_playback_info_product.h",
    "//tizen_src/ewk/efl_integration/public/ewk_media_subtitle_info_product.h",

    # EWebKit.h
    "//tizen_src/ewk/efl_integration/public/ewk_autofill_profile.h",
    "//tizen_src/ewk/efl_integration/public/ewk_back_forward_list.h",
    "//tizen_src/ewk/efl_integration/public/ewk_back_forward_list_item.h",
    "//tizen_src/ewk/efl_integration/public/ewk_context.h",
    "//tizen_src/ewk/efl_integration/public/ewk_context_menu.h",
    "//tizen_src/ewk/efl_integration/public/ewk_cookie_manager.h",
    "//tizen_src/ewk/efl_integration/public/ewk_error.h",
    "//tizen_src/ewk/efl_integration/public/ewk_geolocation.h",
    "//tizen_src/ewk/efl_integration/public/ewk_intercept_request.h",
    "//tizen_src/ewk/efl_integration/public/ewk_main.h",
    "//tizen_src/ewk/efl_integration/public/ewk_manifest.h",
    "//tizen_src/ewk/efl_integration/public/ewk_policy_decision.h",
    "//tizen_src/ewk/efl_integration/public/ewk_security_origin.h",
    "//tizen_src/ewk/efl_integration/public/ewk_settings.h",
    "//tizen_src/ewk/efl_integration/public/ewk_view.h",

    # EWebKit_internal.h
    "//tizen_src/ewk/efl_integration/public/ewk_application_cache_manager_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_auth_challenge_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_auth_request_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_autofill_credit_card_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_certificate_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_console_message_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_content_screening_detection_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_context_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_context_menu_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_cookie_manager_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_custom_handlers_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_dispatcher_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_enums_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_error_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_favicon_database_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_frame_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_geolocation_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_history_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_hit_test_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_intercept_request_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_ipc_message_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_log_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_main_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_manifest_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_notification_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_object_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_page_group_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_policy_decision_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_popup_menu_item_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_quota_permission_request_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_security_origin_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_settings_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_storage_manager_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_text_style_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_touch_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_tracing_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_user_media_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_view_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_web_application_icon_data_internal.h",
    "//tizen_src/ewk/efl_integration/public/ewk_window_features_internal.h",

    # EWebKit_product.h
    "//tizen_src/ewk/efl_integration/public/ewk_autofill_profile_product.h",
    "//tizen_src/ewk/efl_integration/public/ewk_context_menu_product.h",
    "//tizen_src/ewk/efl_integration/public/ewk_context_product.h",
    "//tizen_src/ewk/efl_integration/public/ewk_cookie_manager_product.h",
    "//tizen_src/ewk/efl_integration/public/ewk_file_chooser_request_product.h",
    "//tizen_src/ewk/efl_integration/public/ewk_form_repost_decision_product.h",
    "//tizen_src/ewk/efl_integration/public/ewk_highcontrast_product.h",
    "//tizen_src/ewk/efl_integration/public/ewk_media_downloadable_font_info_product.h",
    "//tizen_src/ewk/efl_integration/public/ewk_media_parental_rating_info_product.h",
    "//tizen_src/ewk/efl_integration/public/ewk_media_playback_info_product.h",
    "//tizen_src/ewk/efl_integration/public/ewk_media_subtitle_info_product.h",
    "//tizen_src/ewk/efl_integration/public/ewk_settings_product.h",
    "//tizen_src/ewk/efl_integration/public/ewk_value_product.h",
    "//tizen_src/ewk/efl_integration/public/ewk_view_product.h",
  ]
  outputs = [ "$root_gen_dir/ewk_api_wrapper_generated.cc" ]
  out_cpp =
      rebase_path("$root_gen_dir/ewk_api_wrapper_generated.cc", root_build_dir)
  args = [ "--out-cpp=$out_cpp" ]
}

shared_library("ewk-interface") {
  output_name = "chromium-ewk"
  include_dirs = [
    ".",
    "//tizen_src/ewk/efl_integration/public",
  ]
  defines = [
    "APP_RO_ROOT_DIR=\"$app_ro_root_dir\"",
    "LIB_RO_ROOT_DIR=\"$lib_ro_root_dir\"",
    "CHROMIUM_IMPL_LIB_FILE=\"$chromium_impl_lib_name\"",
  ]
  deps = [ ":ewk_api_wrapper_source" ]
  sources = [
    "$root_gen_dir/ewk_api_wrapper_generated.cc",
    "ewk_interface_main.cc",
    "ewk_interface_main.h",
  ]
  if (is_tizen) {
    configs += [
    "//tizen_src/build/config:eina",
    "//tizen_src/build/config:evas"
    ]
  }
  libs = [
    "dlog",
    "dl",
  ]
  ldflags = [ "-Wl,--as-needed",
              "-Wl,--version-script=" +
              rebase_path("//tizen_src/ewk/chromium-ewk.filter") ]
  if (is_samsung_next_browser) {
    configs += [
      "//tizen_src/build/config:capi-appfw-application",
      "//tizen_src/build/config:smart-deadlock",
      "//tizen_src/build/config:libsmart-deadlock",
    ]
    defines += [
      "SAMSUNG_NEXT_BROWSER",
    ]
    sources += [
      "browser_app_control.cc",
      "browser_app_interface.cc",
    ]
  }
  if (tizen_product_tv) {
    defines += [
      "LIB_UPGRADE_ROOT_DIR=\"$lib_upgrade_root_dir\"",
    ]
    configs += [
      "//tizen_src/build/config:capi-system-info",
      "//tizen_src/build/config:launchpad",
      "//tizen_src/build/config:vconf"
    ]
    libs += [ "capi-system-info", "lwipc", "ttrace", "vconf", "launchpad" ]
  }
}

executable("chromium-efl-install") {
  cflags = [
    # Treat warning as error for this target.
    # It needs to be included by means of pattern list because '-Werror' cflag
    # will be excluded in chromium side (src/build/common.gypi), and GYP
    # processes pattern lists after exclusion lists.
    # (ref: https://gyp.gsrc.io/docs/InputFormatReference.md#Processing-Order)
    "-Werror",
  ]
  defines = [
    "PACKAGE_ID=\"$package_id\"",
    "APP_RO_ROOT_DIR=\"$app_ro_root_dir\"",
    "APP_RW_ROOT_DIR=\"$app_rw_root_dir\"",
    "LIB_RO_ROOT_DIR=\"$lib_ro_root_dir\"",
  ]
  if (tizen_product_tv) {
    defines += [
      "APP_UPGRADE_ROOT_DIR=\"$app_upgrade_root_dir\"",
      "LIB_UPGRADE_ROOT_DIR=\"$lib_upgrade_root_dir\"",
    ]
  }
  sources = []
  include_dirs = []
  libs = [
    "dlog",
    "glib-2.0",
  ]
  deps = []
  if (is_tizen) {
    configs += [
      "//tizen_src/build/config/tizen:executable_config",
      "//tizen_src/build/config:glib-2.0",
      ]
    if (symbol_level != 0) {
      configs -= [ "//build/config/compiler:default_symbols" ]
      configs += [ "//build/config/compiler:symbols" ]
    }
    sources += [ "chromium_efl_install.cc" ]
  }
  if (tizen_product_tv) {
    configs += [ "//tizen_src/build/config:privileged-service" ]
    configs += [ "//tizen_src/build/config:cynara-creds-self" ]
    libs += [ "lwipc", "vconf" ]
  }
}
